import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-[1fr_3fr] h-screen">
          <section className="h-full">
            <Sidebar />
          </section>
          <main> {children}</main>
        </div>
        {modal}
      </body>
    </html>
  );
}
