import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import LoginForm from "@/components/login-form";
import { cookies } from "next/headers";
import { adminAuth } from "@/lib/firebaseAdmin";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  let loggedIn = false;

  try {
    const sessionCookie = (await cookies()).get("session")?.value;

    if (sessionCookie) {
      await adminAuth.verifySessionCookie(sessionCookie, true);
      loggedIn = true;
    }
  } catch (error) {
    loggedIn = false;
  }

  return (
    <html lang="en">
      <body>
        {loggedIn ? (
          <div className="grid grid-cols-[1fr_3fr] h-screen">
            <Sidebar />
            <main>{children}</main>
          </div>
        ) : (
          <div className="flex items-center justify-center h-screen">
            <LoginForm />
          </div>
        )}
        {modal}
      </body>
    </html>
  );
}
